---
title: "218X_R6Turnin"
author: "Jordan Brinn"
date: "12/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
library(tidyverse)
library(tigris)
library(sf)
library(mapview)
library(leaflet)
library(plotly)
library(censusapi)
library(mapboxapi)
library(readxl)
library(tidycensus)


Sys.setenv(CENSUS_KEY="0b9dfaf3fa0df7bb9bce2b33001ae985230cc118")
```

#Part 1 - Burden Analysis
```{r}
#set up 
bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

bay_counties <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME %in% bay_county_names)

ca_pumasR6 <-
  pumas("CA", cb = T, progress_bar = F)

bay_pumasR6 <-
  ca_pumasR6 %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(ca_pumasR6 %>% select(GEOID10)) %>% 
  st_as_sf()

pums_vars_2019 <- #changed to 2019
  pums_variables %>%
  filter(year == 2019, survey == "acs1")
```

```{r, eval = F}
#preaggregated housing cost variables - had to change to 2019 because 2014-2018 was too big
ca_pumsR6 <- get_pums(
  variables = c(
    "PUMA",
    "GRNTP", #renter montly costs
    "SMOCP", #owner monthly costs
    "ADJHSG",
    "HINCP",
    "ADJINC"
  ),
  state = "CA",
  year = 2019,
  survey = "acs1"
)
saveRDS(ca_pumsR6,"ca_pumsR6.rds")
```

```{r, echo = F}
#to avoid viewing downloading progress in html
ca_pumsR6 <- readRDS("ca_pumsR6.rds")
bay_pumsR6 <-
  ca_pumsR6 %>% 
  filter(PUMA %in% bay_pumasR6$PUMACE10)
```

```{r}
#filtering pums and pumas data for SF county only
sf_county <-
  bay_counties %>% 
  filter(NAME == "San Francisco")

sf_pumas <-
  bay_pumasR6 %>% 
  st_centroid() %>% 
  .[sf_county, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(bay_pumasR6 %>% select(GEOID10)) %>% 
  st_as_sf()

sf_pums <-
  bay_pumsR6 %>%
  filter(PUMA %in% sf_pumas$PUMACE10)
```

```{r}
#SF housing burden (30%) as a percentage and absolute dollar amount
burden_threshold <- 0.3

sf_burden <-
  sf_pums %>% 
  filter(HINCP > 0) %>%
  filter(SPORDER == 1) %>% 
  transmute(
    PUMA = PUMA,
    weight = WGTP,
    housingcost = ifelse(
      SMOCP > 0,
      SMOCP*12*as.numeric(ADJHSG),
      GRNTP*12*as.numeric(ADJHSG)
    ),
    income = HINCP*as.numeric(ADJINC),
    burden_perc = housingcost/income,
    burden_30 = housingcost - burden_threshold*income,
    incomegap_30 = housingcost/burden_threshold - income,
    status = ifelse(
      SMOCP > 0,
      "Owner",
      "Renter"
    )
  )
```

```{r}
#housing burden summary for Bay Area PUMAs
sf_burden_groups <-
  sf_burden %>% 
  group_by(status) %>% 
  mutate(
    burdened_30 = ifelse(
      (burden_perc >= burden_threshold) ,
        weight,
        0
    ),
    excess_30 = ifelse(
      (burden_30 < 0) ,
      burden_30,
      0
    ),
    burden_30 = ifelse(
      (burden_30 > 0) ,
      burden_30,
      0
    ),
    incomegap_30 = ifelse(
      (incomegap_30 > 0),
      incomegap_30,
      0
    )
  ) 

sf_burden_summary <-
  sf_burden_groups %>% 
    summarize(
    burdened_30 = sum(burdened_30), #number of burdened households (spend 30%+ income on housing)
    households = sum(weight), #number of households 
    burden_30 = sum(burden_30*weight), #total funding that would be required to eliminate this housing burden
    incomegap_30 = sum(incomegap_30*weight), #total increase in income necessary to unburde households that are currently burdened assuming same rent/mortgage payment
    excess_30 = sum(excess_30*weight) #total amount of money that households would have pay for rent/mortage in order to become burdened (negative amount indicates higher total burden than excess)
  ) %>% 
  mutate(
    burdened_30_perc = burdened_30/households #percent of households burdened in San Francisco County 
  ) 

sf_burden_summary
```

```{r}
#joining pumas to burdened pums data, grouped by puma and renter/owner status
sf_burden_pumas <-
  sf_burden_groups %>% 
  group_by(PUMA, status) %>%
  summarize(
    burdened_30 = sum(burdened_30),
    households = sum(weight),
    burden_30 = sum(burden_30*weight),
    incomegap_30 = sum(incomegap_30*weight),
    excess_30 = sum(excess_30*weight)
  ) %>% 
  mutate(
    burdened_30_perc = burdened_30/households
  ) %>% 
  left_join(bay_pumasR6 %>% select(PUMA = PUMACE10)) %>% 
  st_as_sf()
```

```{r}
#Map of Owner households paying 30%+ of their income
burden_pal1 <- colorNumeric(
  palette = "Purples",
  domain = sf_burden_pumas %>% 
    filter(
      status == "Owner"
    ) %>% 
    pull(burdened_30_perc)
)

sf_burden_pumas %>% 
  filter(
    status =="Owner"
  ) %>% 
  leaflet() %>% 
  addMapboxTiles(
    style_id = "streets-v11",
    username = "mapbox"
  ) %>% 
  addPolygons(
    fillColor = ~burden_pal1(burdened_30_perc),
    fillOpacity = 0.5,
    color = "white",
    weight = 0.5,
    label = ~paste0(round(burdened_30_perc*100), "% of households paying 30%+ of income on housing"),
    highlightOptions = highlightOptions(
      weight = 2
    )
  ) %>% 
  addLegend(
    pal = burden_pal1,
    values = ~burdened_30_perc,
    title = "% Cost-burdened<br>households"
  )
```

```{r}
#Map of % of Renter households paying 30%+ of income 
burden_pal1 <- colorNumeric(
  palette = "Blues",
  domain = sf_burden_pumas %>% 
    filter(
      status == "Renter"
    ) %>% 
    pull(burdened_30_perc)
)

sf_burden_pumas %>% 
  filter(
    status =="Renter"
  ) %>% 
  leaflet() %>% 
  addMapboxTiles(
    style_id = "streets-v11",
    username = "mapbox"
  ) %>% 
  addPolygons(
    fillColor = ~burden_pal1(burdened_30_perc),
    fillOpacity = 0.5,
    color = "white",
    weight = 0.5,
    label = ~paste0(round(burdened_30_perc*100), "% of households paying 30%+ of income on housing"),
    highlightOptions = highlightOptions(
      weight = 2
    )
  ) %>% 
  addLegend(
    pal = burden_pal1,
    values = ~burdened_30_perc,
    title = "% Cost-burdened<br>households"
  )
```



#Part 2 - Property Uses and Zoning
```{r}
#shapes of SF parcels from Open Data Portal 
sf_parcels_shape <- 
  st_read("https://data.sfgov.org/api/geospatial/acdm-wktn?method=export&format=GeoJSON") %>% 
  filter(active == "true") %>% 
  select(
    apn = blklot,
    zoning = zoning_code,
    zoning_desc = zoning_district
  )
```

```{r}
#SF assessor-recorder propert tax roll data
temp <- tempfile()
download.file("https://sfassessor.org/sites/default/files/uploaded/2020.7.10_SF_ASR_Secured_Roll_Data_2019-2020.xlsx",destfile = temp, mode = "wb")

sf_secured <- read_excel(temp, sheet = "Roll Data 2019-2020")
datakey <- read_excel(temp, sheet = "Data Key")
usecode <- read_excel(temp, sheet = "Class Code Only")

unlink(temp)

datakey %>% select(`DATA NAME`, `FIELD NAME`) %>% as.data.frame()
```

```{r}
#joining property tax data to parcel shape df - will be errors
sf_parcels <-
  sf_parcels_shape %>% 
  left_join(
    sf_secured %>% 
      mutate(
        apn = RP1PRCLID %>% 
          str_replace(" ","")
      )
  )

sum(!is.na(sf_parcels$apn)) #how many APNs sf_parcel starts with 
sum(!is.na(sf_parcels$RP1PRCLID)) #how many APNs are successfully matched with sf_secured
sum(!is.na(sf_parcels$zoning)) #how many records in sf_parcels have zoning codes
sum(!is.na(sf_parcels$ZONE)) #how many of the matched records from sf_secrued have zoning codes

```

```{r}
#Parcel data for my census tract (Asbury Heights/Haight/Cole Valley) 
my_sample <-
  tracts("CA", "San Francisco", cb = T, progress_bar = F) %>% 
  filter(
    TRACTCE %in% c(
      "017101"
    )
  ) %>% 
  st_transform(4326)

my_parcel <- 
  sf_parcels %>% 
  st_centroid() %>% 
  .[my_sample, ] %>% 
  st_set_geometry(NULL) %>% 
  left_join(sf_parcels %>% select(apn)) %>% 
  st_as_sf() %>% 
  filter(!is.na(RP1PRCLID))

my_parcel %>% 
  leaflet() %>% 
  addMapboxTiles(
    style_id = "streets-v11",
    username = "mapbox"
  ) %>% 
  addPolygons(
    fillColor = "blue",
    color = "black",
    weight = 0.5,
    label = ~zoning
  )
```
```{r}
#which parcel records are conodminiumized 
duplicate_shapes <- 
  my_parcel %>% 
  as.data.frame() %>% 
  filter(duplicated(geometry))

condo_parcels <- 
  my_parcel %>% 
  filter(geometry %in% duplicate_shapes$geometry)
```

```{r}
#what zones are included in my tract
my_parcel %>%
  st_set_geometry(NULL) %>% 
  group_by(zoning, zoning_desc) %>% 
  summarize(Freq = n())
#RH = Residential House Districts, RM = Residential Mixed Use Districts, P = Public Use
#RH-1(D) - One Family (attached dwelling) - single family houses with side yards (wider lots, less than 35ft)
#RH-2 - Two Family - less than 25ft wide by 40ft tall, one and two family houses, owner usually occupies one of the two family units
#RH-2|RH-1(D) --> covert to RH-2
#RH-3 - Three Family - 3 units common in addition to one and two, usually flats not apartments, nonresidential uses more common than in RH-2, ground floor outdoor spaces and decks
#RH-2|RH-2 --> convert to RH-3
#RM-1 - Low Density - mixture of dwelling types, lots of apartment buildings, generally 25-35 ft wide and 40 ft high. Separate entrances for groups of units, ground floor and top floor outdoor spaces, nonresidential uses
```

```{r}
#summary of stats
table(my_parcel$RP1CLACDE) %>% 
  as.data.frame() %>% 
  left_join(usecode, by = c("Var1"= "CODE")) %>% 
  select(Freq, DESCRIPTION)
```
```{r}
#cleaning data of parcel to filter out public property, convert zones listed under two codes to one code, and add a column with potential building height based on zoning
my_parcel_clean <-
  my_parcel %>% 
  mutate(
    zoning = case_when(
      zoning == "RH-2|RH-1(D)" ~ "RH-2",
      zoning == "RH-3|RH-2" ~ "RH-3",
      TRUE ~ zoning
    )
  ) %>% 
  filter(zoning != "P") %>% 
  as.data.frame() %>% 
  mutate(geometry = geometry %>% st_as_text()) %>% 
  group_by(geometry) %>% 
  summarize(
    apn = first(apn),
    zoning = first(zoning),
    units = sum(UNITS, na.rm = T),
    stories = max(STOREYNO, na.rm = T),
    floorarea = sum(SQFT, na.rm = T)
  ) %>% 
  ungroup() %>%
  select(-geometry) %>% 
  left_join(my_parcel %>% select(apn)) %>% 
  st_as_sf() %>% 
  mutate(
    gen_hght = ifelse(
      zoning == "RM-1",
      40,
      35
    )
  )
```

```{r}
#create and append max_floorarea, max_units, and max_stories to existing dataframe. create unused_floorarea, unused_units, and unused_stories (max - current)

projection <- "+proj=utm +zone=10 +ellps=GRS80 +datum=NAD83 +units=ft +no_defs" #want in sqft

my_parcel_zoning <-
  my_parcel_clean %>% 
  st_centroid() %>% 
  st_set_geometry(NULL) %>% 
  left_join(my_parcel_clean %>% select(apn)) %>% 
  st_as_sf() %>% 
  st_transform(projection) %>% 
  mutate(
    lotarea = st_area(.) %>% as.numeric(), #need numeric because in units format
    max_floorarea =  lotarea*1.8,
    unused_floorarea = ifelse(
      (max_floorarea - floorarea) > 0,
      (max_floorarea - floorarea),
      0
    ),
    max_units = case_when(
      zoning == "RH-1(D)" ~ 1,
      zoning == "RH-2" ~ 2,
      zoning == "RH-3" ~ 3,
      zoning == "RM-1" ~ pmax(3, floor(lotarea/800)), #pmax finds highest of value set
    ),
    unused_units = ifelse(
      (max_units - units) > 0,
      (max_units - units),
      0
    ),
    max_height = gen_hght ,
    max_stories = floor(max_height/11),
    unused_stories = ifelse(
      (max_stories - stories) > 0,
      (max_stories - stories),
      0
    )
  ) %>% 
  st_transform(4326)

#indicates underutilization based on current zoning
sum(my_parcel_zoning$unused_floorarea, na.rm = T) #total unused floor area in parcel
sum(my_parcel_zoning$unused_units, na.rm = T) #total unused units in parcel
```

```{r}
#plot of unused floor area
floorarea_pal <- colorBin(
  palette = "Greens",
  bins = c(0,1000,5000,10000,max(my_parcel_zoning$unused_floorarea, na.rm = T))
) #manually set bins because of high outliers (5 in 10,000-20,000 range) --> the plots along buena vista have been under construction for 6 months now, so maybe this will improve

leaflet() %>% 
  addMapboxTiles(
    style_id = "light-v9",
    username = "mapbox"
  ) %>% 
  addPolygons(
    data = my_parcel_zoning,
    fillColor = ~floorarea_pal(unused_floorarea),
    fillOpacity = 0.75,
    color = "white",
    weight = 0.5,
    label = ~round(unused_floorarea)
  ) %>% 
  addLegend(
    data = my_parcel_zoning,
    pal = floorarea_pal,
    values = ~unused_floorarea,
    title = "Unused Floor Area"
  )
```

```{r}
#plot of additional allowed units (#unused units)
units_pal <- colorBin(
  palette = "Purples",
  bins = c(0,1,2,3) #no unused > 3
)

leaflet() %>% 
  addMapboxTiles(
    style_id = "light-v9",
    username = "mapbox"
  ) %>% 
  addPolygons(
    data = my_parcel_zoning,
    fillColor = ~units_pal(unused_units),
    fillOpacity = 0.75,
    color = "white",
    weight = 0.5,
    label = ~round(unused_units)
  ) %>% 
  addLegend(
    data = my_parcel_zoning,
    pal = units_pal,
    values = ~unused_units,
    title = "Additional Units<br>Allowed"
  )
```

```{r}
#ggplot of unused stories instead of leaflet
my_stories_plot <- 
  my_parcel_zoning %>% 
  filter(unused_stories > 0) %>% 
  ggplot() + 
  geom_sf(
    aes(
      fill = unused_stories
    ),
    lwd = 0
  ) + 
  theme(
    axis.text.x = element_blank(), 
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    rect = element_blank()
  ) +
  labs(
    fill = "Unused Stories"
  ) +
  scale_fill_gradient(
    low = "white",
    high = "red"
  )

#indicates greatest potential in Special Height Districts
my_stories_plot
```

```{r}
#stories plot in 3D
library(rayshader)

plot_gg(
  my_stories_plot,
  width = 10,
  height = 4,
  scale = 100
)

render_snapshot(
  "snapshot.png",
  clear = TRUE
)
```



